# Generated by Django 3.0.7 on 2020-07-02 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t', to=settings.AUTH_USER_MODEL)),
                ('roomName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j', to='chat.Room')),
            ],
        ),
    ]
