# Generated by Django 3.0.8 on 2020-10-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_auto_20201023_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='unique_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
